title:     EJS
author:    Erica
timezone:  America/New_York
markdown:  kramdown
url:       "http://www.ericajs.github.io"

description: > #
  Action will delineate and define you. That fabled lighted feather’s counterpart lies ever hidden in each bird’s heart.

twitter:     "http://twitter.com/ericajaclyn"
github:      "https://github.com/ericajs"
medium:      "https://medium.com/@ericajaclyn"
linkedin:    "https://linkedin.com/ericajaclynstein"
dribbble:    "http://www.dribbble.com/ericajaclyn"

collections:
    resources:
       output: true
       permalink: /:path/
    projects:
        output: true
        permalink: /:path/
