title: arythmetically
author: Erica
description: > #
  Human-Information Interaction
baseurl: ""
url: "http://www.ericajaclynstein.github.io"

# CONFIGURATION
markdown:    kramdown

# OUTPUT
timezone: America/New_York

# BASIC SOCIAL MEDIA
twitter: "http://twitter.com/ericajaclyn"
github:  "https://github.com/ericajaclynstein"
medium: "https://medium.com/@ericajaclyn"
linkedin: "https://linkedin.com/ericajaclynstein"
dribbble: "http://www.dribbble.com/ericajaclyn"
google_plus: "https://plus.google.com/+EricaJaclynStein"