title:     That fabled lighted feather’s counterpart lies ever hidden in each bird’s heart.
author:    Erica
timezone:  America/New_York
markdown:  kramdown
url:       "http://www.wearethedesigners.com"

description: > #
  Action will delineate and define you. 

twitter:     "http://twitter.com/ericajaclyn"
github:      "https://github.com/ericajaclynstein"
medium:      "https://medium.com/@ericajaclyn"
linkedin:    "https://linkedin.com/ericajaclynstein"
dribbble:    "http://www.dribbble.com/ericajaclyn"
google_plus: "https://plus.google.com/+EricaJaclynStein"

collections:
    resources:
       output: true
       permalink: /:path/
    projects: 
        output: true
        permalink: /:path/
