title: HII
author: Erica
description: > # this means to ignore newlines until "baseurl:"
  Human-Information Interaction
  
baseurl: ""
url: "http://www.ericajaclynstein.github.io"

markdown: redcarpet
timezone: America/New_York

# BASIC SOCIAL MEDIA

twitter: "http://twitter.com/ericajaclyn"
github:  "https://github.com/ericajaclynstein"
medium: "https://medium.com/@ericajaclyn"
linkedin: "https://linkedin.com/ericajaclynstein"
dribbble: "http://www.dribbble.com/ericajaclyn"
google_plus: "https://plus.google.com/+EricaJaclynStein"

# COLLECTIONS

collections:
  projects:
    layout: page
    output: true
    title: 